# Generated by Django 5.0.7 on 2024-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rôle',
            field=models.CharField(choices=[('admin', 'Admin'), ('acheteur', 'Acheteur'), ('particulier', 'Particulier'), ('boutiques', 'Boutiques'), ('supermarket', 'Super-Marché'), ('superette', 'Superette'), ('station', 'Station-Service')], default='acheteur', max_length=255),
        ),
    ]
