# Generated by Django 5.0.7 on 2024-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0002_alter_customuser_rôle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nom_boutique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
