# Generated by Django 5.0.7 on 2024-09-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0003_customuser_nom_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
