# Generated by Django 5.0.7 on 2024-09-18 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0007_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='SunApp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
