# Generated by Django 5.0.7 on 2024-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0008_facture_product_alter_facture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
