# Generated by Django 5.0.7 on 2024-09-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0011_notification_is_read_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
