# Generated by Django 5.0.7 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0013_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Électronique'), ('fashion', 'Mode et Vêtements'), ('home_garden', 'Maison et Jardin'), ('beauty_health', 'Beauté et Santé'), ('food_drink', 'Alimentation et Boissons'), ('sports_leisure', 'Sport et Loisirs'), ('books_media', 'Livres et Médias'), ('toys_kids', 'Jouets et Enfants'), ('automotive_tools', 'Automobile et Outils'), ('pets', 'Animaux'), ('services', 'Services et Abonnements'), ('special_offers', 'Offres spéciales / Promotions')], default='electronics', max_length=50),
        ),
    ]
