# Generated by Django 5.0.7 on 2024-12-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunApp', '0015_product_pays_product_quartier_product_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rôle',
            field=models.CharField(choices=[('admin', 'Admin'), ('acheteur', 'Acheteur'), ('particulier', 'Particulier'), ('boutiques', 'Boutiques'), ('supermarket', 'Super-Marché'), ('imobilier', 'Imobilier')], default='acheteur', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
